name: Automated Workflow

on:
  issues:
    types:
      - opened

jobs:
  move-to-ready:
    runs-on: ${{ matrix.os }}
    env:
      PROJECT_ID: 6 # Reemplaza con el ID real de tu proyecto
    strategy:
      matrix:
        os: [ windows-latest]

    steps:
      - name: Move Issue to Ready Column
        uses: actions/github-script@v7
        with:
            github-token: ${{ secrets.GITHUB_TOKEN }}
            script: |
            const { data: projectColumns } = await github.projects.listColumns({ project_id: process.env.PROJECT_ID });
            const readyColumn = projectColumns.find(column => column.name === 'Ready');
            
            await github.projects.moveCard({
              card_id: context.payload.issue.card_id,
              position: 'top',
              column_id: readyColumn.id,
            });

  
