name: Automated Workflow

on:
  issues:
    types:
      - opened

jobs:
  move-to-ready:
    runs-on: ${{ matrix.os }}
    env:
      PROJECT_ID: 6 # Reemplaza con el ID real de tu proyecto
    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - name: Move Issue to Ready Column
        run: |
          # Obtener el token de GitHub
          $GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          
          # Obtener el ID del proyecto
          $PROJECT_ID=${{ env.PROJECT_ID }}
          
          # Obtener el ID de la tarjeta
          $CARD_ID = (Invoke-RestMethod -Headers @{Authorization="Bearer $GITHUB_TOKEN"} -Uri "https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/cards").id
          
          # Listar proyectos usando la API REST de GitHub
          $PROJECTS = Invoke-RestMethod -Headers @{Authorization="Bearer $GITHUB_TOKEN"} -Uri "https://api.github.com/repos/${{ github.repository }}/projects"
          
          # Extraer el ID de la columna 'Ready'
          $READY_COLUMN_ID = ($PROJECTS | Where-Object { $_.name -eq "Ready" }).columns.id
          
          # Mover la tarjeta a la columna 'Ready'
          Invoke-RestMethod -Method Post -Uri "https://api.github.com/projects/columns/cards/$CARD_ID/moves" -Headers @{Authorization="Bearer $GITHUB_TOKEN"; Accept="application/vnd.github.inertia-preview+json"} -Body ("{\"position\": \"top\", \"column_id\": \"$READY_COLUMN_ID\"}")
